# THIS IS HEADING 1(H1 TAG)
## H2
### H3
#### H4
##### H5
###### H6



 # NUMPY
 Numarical Python 
 it is multidimensional
 it is less time to execute
 you can perform the numarical operation
 

In [3]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [5]:
d1=np.array([45,74,85,36,65,57])
d1

array([45, 74, 85, 36, 65, 57])

In [6]:
d1.shape

(6,)

In [7]:
d1.size

6

In [8]:
d1.ndim

1

In [9]:
d1[0]

45

In [10]:
d1[2]

85

In [11]:
d1[10]

IndexError: index 10 is out of bounds for axis 0 with size 6

In [12]:
d1[0,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [13]:
d1[0:3]

array([45, 74, 85])

In [14]:
data = np.array(["range",123,"CSE","A",9.8])
data

array(['range', '123', 'CSE', 'A', '9.8'], dtype='<U5')

In [17]:
import time
start_time=time.time()
list1 = [X for X in range(1,100000)]
list2 = [Y for Y in range(1,100000)]
output=list(map(lambda X,Y:X*Y,list1,list2))
end_time=time.time()
print("time taken by list concept",end_time-start_time)

time taken by list concept 0.023992061614990234


In [18]:
import time
start_time1=time.time()

ar1 = np.array(list1)
ar2 = np.array(list2)

ar1*ar2
end_time1=time.time()
print("time taken by numpy concept",end_time1-start_time1)

time taken by numpy concept 0.01999497413635254


In [19]:
#2D array
d2 = np.array([[43,76,34],[98,67,88],[46,77,60]])
d2


array([[43, 76, 34],
       [98, 67, 88],
       [46, 77, 60]])

In [20]:
d2.shape

(3, 3)

In [21]:
d2.size

9

In [22]:
d2.ndim

2

In [23]:
d2[2]

array([46, 77, 60])

In [24]:
d2[0][1]

76

In [25]:
max(d2[1])

98

In [26]:
np.max(d2[1])

98

In [28]:
d2[:,2]

array([34, 88, 60])

In [29]:
max(d2[:,2])

88

In [30]:
d2[:,2].max()

88

In [31]:
min(d2[:,2])

34

In [32]:
d2[:,2].min()

34

In [34]:
d2[:,2].sum()

182

In [35]:
d2[:,1].sum()

220

In [36]:
d2[:,0].sum()

187

In [37]:
d2.sum()

589

In [38]:
d2.sum(axis=0)

array([187, 220, 182])

In [39]:
d2.sum(axis=1)

array([153, 253, 183])

In [41]:
d3 = np.array([[[1,3,4],[5,6,8],[7,11,9],[21,66,98]]])
d3

array([[[ 1,  3,  4],
        [ 5,  6,  8],
        [ 7, 11,  9],
        [21, 66, 98]]])

In [42]:
d3[0,0]

array([1, 3, 4])

In [43]:
d3[0,0,0]

1

# arange()

In [44]:
l1 = [x for x in range(1,10)]

In [45]:
print(l1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [47]:
arange(1,10)

NameError: name 'arange' is not defined

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
for i in range(1,10,0.5)
print(i,end=" ")

SyntaxError: invalid syntax (<ipython-input-51-e4b114e91ae1>, line 1)

In [52]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [53]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [54]:
# zero matrix
print(np.zeros([3,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [55]:
print(np.ones([3,5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [58]:
np.array([[14,25,36,41,52],[24,51,25,15,12]])

array([[14, 25, 36, 41, 52],
       [24, 51, 25, 15, 12]])

In [59]:
d21=np.array([[14,25,36,41,52],[24,51,25,15,12]])
d21

array([[14, 25, 36, 41, 52],
       [24, 51, 25, 15, 12]])

In [61]:
add_marks = np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [62]:
final_marks=d21+add_marks

In [63]:
final_marks

array([[19, 30, 41, 46, 57],
       [29, 56, 30, 20, 17]])

In [64]:
mat = np.array([[1,23,4],[23,43,12],[21,7,8]])
mat

array([[ 1, 23,  4],
       [23, 43, 12],
       [21,  7,  8]])

In [65]:
np.linalg.inv(mat)

array([[-0.22727273,  0.13636364, -0.09090909],
       [-0.05944056,  0.06643357, -0.06993007],
       [ 0.6486014 , -0.41608392,  0.42482517]])

In [66]:
np.linalg.eig(mat)

(array([56.95015766, -7.59501593,  2.64485827]),
 array([[-0.38157338, -0.6133844 , -0.18585051],
        [-0.87791828,  0.09281751, -0.18124213],
        [-0.28924256,  0.78431147,  0.9657178 ]]))

In [67]:
np.random.random(10)

array([0.31934016, 0.40458191, 0.95370017, 0.38350651, 0.80057738,
       0.17216113, 0.66192016, 0.61830316, 0.58545572, 0.42015264])

In [68]:
np.random.randint(10)

6

In [69]:
np.random.randint(10,20)

10

In [70]:
np.random.randint(10,20)

14

In [71]:
np.random.randint(10,20,30)

array([17, 17, 17, 18, 19, 10, 17, 10, 18, 11, 17, 19, 18, 13, 14, 11, 17,
       14, 15, 12, 14, 14, 18, 15, 16, 12, 11, 10, 10, 11])

In [73]:
np.random.randint(10,25,[4,6])

array([[14, 12, 24, 21, 17, 19],
       [21, 22, 20, 22, 11, 19],
       [21, 17, 23, 10, 24, 21],
       [22, 18, 10, 22, 20, 18]])

In [74]:
np.random.rand(10)

array([0.80093782, 0.14442569, 0.17161389, 0.4874192 , 0.10426847,
       0.95581439, 0.69380497, 0.69885885, 0.11237293, 0.37547224])

In [75]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])