In [2]:
import numpy as np

In [3]:
np.sin(90)

0.8939966636005579

In [4]:
np.cos(0)

1.0

In [6]:
np.tan(45)

1.6197751905438615

In [8]:
np.sinh(10)

11013.232874703393

In [11]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
array.max()

9

In [13]:
array.min()

1

In [14]:
array.argmax()

8

In [20]:
array.argmin()

0

In [25]:
section1 = np.array(np.random.randint(10,20,[4,4]))
section1

array([[14, 16, 10, 16],
       [19, 17, 10, 10],
       [19, 11, 19, 17],
       [17, 17, 17, 15]])

In [19]:
sec2 = np.array(np.random.randint(1,10,[4,4]))
sec2

array([[4, 3, 1, 4],
       [7, 1, 6, 7],
       [3, 7, 5, 5],
       [4, 8, 1, 6]])

In [22]:
np.vstack((section1,sec2))

array([[19, 19, 15, 12],
       [12, 12, 15, 18],
       [ 4,  3,  1,  4],
       [ 7,  1,  6,  7],
       [ 3,  7,  5,  5],
       [ 4,  8,  1,  6]])

In [26]:
np.hstack((section1,sec2))

array([[14, 16, 10, 16,  4,  3,  1,  4],
       [19, 17, 10, 10,  7,  1,  6,  7],
       [19, 11, 19, 17,  3,  7,  5,  5],
       [17, 17, 17, 15,  4,  8,  1,  6]])

In [27]:
section1+sec2

array([[18, 19, 11, 20],
       [26, 18, 16, 17],
       [22, 18, 24, 22],
       [21, 25, 18, 21]])

In [28]:
section1*sec2

array([[ 56,  48,  10,  64],
       [133,  17,  60,  70],
       [ 57,  77,  95,  85],
       [ 68, 136,  17,  90]])

In [29]:
section1@sec2

array([[262, 256, 176, 314],
       [265, 224, 181, 305],
       [278, 337, 197, 350],
       [298, 307, 219, 362]])

In [32]:
section1.dot(sec2)

array([[262, 256, 176, 314],
       [265, 224, 181, 305],
       [278, 337, 197, 350],
       [298, 307, 219, 362]])

In [34]:
section1.transpose()

array([[14, 19, 19, 17],
       [16, 17, 11, 17],
       [10, 10, 19, 17],
       [16, 10, 17, 15]])

In [35]:
section1.trace()

65

In [37]:
np.split(sec2,[2,2])

[array([[4, 3, 1, 4],
        [7, 1, 6, 7]]),
 array([], shape=(0, 4), dtype=int32),
 array([[3, 7, 5, 5],
        [4, 8, 1, 6]])]

In [38]:
np.abs(100.25)

100.25

In [40]:
np.all(section1>2)

True

In [43]:
np.all(section1<0)

False

In [44]:
np.round(3.45)

3.0

In [45]:
np.ceil(3.45)

4.0